apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Set to the name of your IngressClass (e.g., "nginx")
  rules:
  - host: pbh-devsecops.in  # Your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-service  # Your service name
            port:
              number: 80